### ISSUE TITLE
Fix uneven cards in management panel

### ISSUE THREAD

**Issue by asynchroza** [AUBGTheHUB/monolith#138]
## Brief description:
![image](https://user-images.githubusercontent.com/104720011/208720863-f4b23f6c-8f57-4a0a-a122-b527900f7f6b.png)

When a card has a string with more characters than usual, they grow bigger and do not look good in the management panel. 
## How to achieve it:
Set a bigger default size or add text wrapping

**Comment by asynchroza** [comment]
@SuelaCark was this fixed?

**Comment by SuelaCark** [comment]
> @SuelaCark was this fixed?

I am not certain if the cards alignment is precise up to the smallest milimeter. However, the changes I made definitely made the alignment better than it was before.

**Comment by asynchroza** [comment]
> > @SuelaCark was this fixed?
> 
> 
> 
> I am not certain if the cards alignment is precise up to the smallest milimeter. However, the changes I made definitely made the alignment better than it was before.

Thank you for working on this! I will be closing this one for now and bring it back up if somebody decides that the current fix is insufficient.
