### ISSUE TITLE
Clean up API readme - rewrite in markdown

### ISSUE THREAD

**Issue by asynchroza** [AUBGTheHUB/monolith#18]
You can use `VSCode` to see the parsed version of the `markdown` file by clicking on the displayed icon (top right corner when editor is open):

![image](https://user-images.githubusercontent.com/104720011/202296862-cff21d9e-e46d-4e23-ae30-d7ad5858ac66.png)

Refer to the following markdown [documentation](https://www.markdownguide.org/cheat-sheet) 

Make sure you are working on a branch! Refer to the following [wiki](https://github.com/AUBGTheHUB/spa-website-2022/wiki/How-to-work-with-Issues-and-Pull-Requests)

PATH to the file is: `packages/api/README.md`

**Comment by asynchroza** [comment]
@IvanObreshkov @peti-krl hey guys, can you wrap up this PR after the hackathon? You can use an online converter to convert most of the text but some part might need to be manually done. 

Additionally, can you add the new routes which were implemented by you?

**Comment by IvanObreshkov** [comment]
> @IvanObreshkov @peti-krl hey guys, can you wrap up this PR after the hackathon? You can use an online converter to convert most of the text but some part might need to be manually done.
> 
> Additionally, can you add the new routes which were implemented by you?

Deal
