### ISSUE TITLE
[OBJECT UPLOADER] Delete an image by url

### ISSUE THREAD

**Issue by asynchroza** [AUBGTheHUB/monolith#415]
In our new python API, we have an uploader which uploads image files to an AWS S3 object storage. You can test it yourself by logging into the admin panel and heading to the Image Management section. By clicking on the button on the top you will be redirected to a page which renders all of the images we have stored in S3. You will see a lot of redundancy there. That's why we want to implement a deleting functionality which needs to be able to somehow figure out what object to delete by the url of the image. From the top of my head, you can just strip out the last endpoint which is the name of the file and use boto3 to pass the name and delete the object. This is a backend ticket, no frontend implementation will be needed here.

**Comment by SuelaCark** [comment]
I am working on the frontend part of the Delete button and its functionality in this branch --> 414-s3-styling-update
I might be able to also work on adjusting the python script so it will implement the delete functionality in the backend/cloud.

**Comment by asynchroza** [comment]
> I am working on the frontend part of the Delete button and its functionality in this branch --> 414-s3-styling-update I might be able to also work on adjusting the python script so it will implement the delete functionality in the backend/cloud.

Good. I will be updating the python env setup docs promptly.

**Comment by asynchroza** [comment]
@SuelaCark would you like to tackle this [one](https://github.com/AUBGTheHUB/spa-website-2022/issues/145) as well? We should probably do the conversion png/jpeg/* -> webp within the service.

**Comment by asynchroza** [comment]
@SuelaCark have you done any relevant work here? I'm thinking of closing this one as the team is going to be migrating the service and I will be rewriting most of the tickets.

**Comment by SuelaCark** [comment]
> @SuelaCark have you done any relevant work here? I'm thinking of closing this one as the team is going to be migrating the service and I will be rewriting most of the tickets.

I didn't work on this since it was not a priority at the time and we had a few discussions about remaking the API and/or creating a whole new website. Hence, I didn't work on this ticket since it was not decided whether we will work on this code.

**Comment by asynchroza** [comment]
Since I didn't implement this when migrating the service, I'm leaving this ticket open. I suggest that either @DemonHashira or @savinadd try to tackle it. If you decide to do so and have any questions at all, don't hesitate to ask either me or @IvanObreshkov.
