### ISSUE TITLE
[STORY] Export hackathon related info from DB as a csv file

### ISSUE THREAD

**Issue by asynchroza** [AUBGTheHUB/monolith#427]
I would suggest story to be done by one person.

## Brief description:
* PR asked for us to export our data to an excel sheet. @nikolayninov and I decided that we will be exporting the data to `.csv`
* Frontend should have a card which would display `Hackathon Summary` - onClick -> it would render the .csv file in the browser ([a helpful resource](https://dev.to/theallegrarr/read-csv-files-in-react-apps-without-installing-any-package-hn7))
* Rendered version of .csv file should be displaying primary data such as the total amount of participants and other key factors such as predominant age and location
* Rendered component should have a button `download sheet` which will download the file as a csv file to the user's computer

This ticket will need work on both the frontend and backend.

**Comment by asynchroza** [comment]
@nikolayninov is this worth investing in? Do we need the metrics or I can close it out?

**Comment by IvanObreshkov** [comment]
@r-mishev @nikolayninov Any new info or updates here?

**Comment by IvanObreshkov** [comment]
@Aleks1908 GJ
