### ISSUE TITLE
Fix css classnames in admin panel [NEXT YEAR]

### ISSUE THREAD

**Issue by SuelaCark** [AUBGTheHUB/monolith#442]
ClassNames used for the admin panel css are confusing and not well-descriptive. For instance, "members-card" is not a good descriptive name for the jobs card in admin panel since it can be confused with other files. Therefore, we need to rename the classNames to hold more specific and descriptive names correlating to their respective files and functions.

**Comment by iusamahub** [comment]
Hi @SuelaCark is it still available? 
I would like to work on it.

**Comment by asynchroza** [comment]
@SuelaCark `members-card` is a global className for all of the cards, not specifically for the jobs cards. But yeah, I agree we have to come up with more descriptive classNames.
