### ISSUE TITLE
(Cannot declare ('package', 'dependencies')

### ISSUE THREAD

**Issue by IvanObreshkov** [AUBGTheHUB/monolith#481]
## Brief description:
![image](https://github.com/AUBGTheHUB/monolith/assets/38375079/9dd2e64a-b0a0-404a-aa38-900c5176e1ce)
![image](https://github.com/AUBGTheHUB/monolith/assets/38375079/aae45d34-6a33-4d51-8770-259c2f904441)

## How to achieve it:
Fix it

**Comment by asynchroza** [comment]
Fixed in the latest commit to master
