### ISSUE TITLE
[FEATURE] Add section for Feature Switches in Admin Panel

### ISSUE THREAD

**Issue by asynchroza** [AUBGTheHUB/monolith#483]
Extension of #463 

All required endpoints have been implemented. 
What's left now is to set up a nice UI for managing said feature switches.

Functionality:
* One should be able to create/update/delete a switch - you should pass `auth_token` as BEARER-TOKEN (Note that we have an upset request instead of two separate methods for creating/updating).
* List all switches

```javascript
// automatically generated example from POSTMAN
// refer to feature_switches.js to see how the request to the endpoint is being made

const axios = require('axios');
let data = JSON.stringify({
  "switch_id": "jobs",
  "is_enabled": "true"
});

let config = {
  method: 'put',
  maxBodyLength: Infinity,
  url: 'localhost:6969/v2/fswitches',
  headers: { 
    'BEARER-TOKEN': 'OFFLINE_TOKEN', 
    'Content-Type': 'application/json'
  },
  data : data
};

axios.request(config)
.then((response) => {
  console.log(JSON.stringify(response.data));
})
.catch((error) => {
  console.log(error);
});

```

<img width="694" alt="image" src="https://github.com/AUBGTheHUB/monolith/assets/104720011/d72a495e-4440-44f9-be0f-d6dfffa6672f">

**Comment by asynchroza** [comment]
@Aleks1908 as already discussed in person, there's no need to be making a request. Use the `useContext` hook to fetch the current state of the fswitches in children components.

**Comment by Aleks1908** [comment]
> @Aleks1908 as already discussed in person, there's no need to be making a request. Use the `useContext` hook to fetch the current state of the fswitches in children components.

I have made it not to make request on initial load but only when an actions has been done. In the render_switch.jsx I have a method getSwitches that renders the switches from feature_switches.js

**Comment by Aleks1908** [comment]
> > @Aleks1908 as already discussed in person, there's no need to be making a request. Use the `useContext` hook to fetch the current state of the fswitches in children components.
> 
> I have made it not to make request on initial load but only when an action(delete, update, add new) has been done. In the render_switch.jsx I have a method getSwitches that renders the switches from feature_switches.js

But it seems that I have forgotten to put # when making the commits and you cannot check what I have done. I need to finish with the UI cuz its buggy rn but the functionality works

**Comment by asynchroza** [comment]
> > > @Aleks1908 as already discussed in person, there's no need to be making a request. Use the `useContext` hook to fetch the current state of the fswitches in children components.
> 
> > 
> 
> > I have made it not to make request on initial load but only when an action(delete, update, add new) has been done. In the render_switch.jsx I have a method getSwitches that renders the switches from feature_switches.js
> 
> 
> 
> But it seems that I have forgotten to put # when making the commits and you cannot check what I have done. I need to finish with the UI cuz its buggy rn but the functionality works

You've overwritten the current logic to not load the switches on initial page load but only when the actions button of the panel is being clicked? Correct me if I'm misunderstanding.

**Comment by asynchroza** [comment]
* All successful requests should use the destructured function from useContext to update the state of the switches.

* Loading the switches on initial page load and updating the state using the useContext hook is mandatory. If we don't do this, the page won't render or disable the corresponding to the switches components.

**Comment by Aleks1908** [comment]
I am not sure what do you mean by not load the switches but. Right now when opening the page for the first time I dont make a request to the API because we have the switches stored. And after that on action I make an request to the API and i get the result from the request and i render the new switches
