### ISSUE TITLE
[BUG] Logger won't display level INFO and won't use uvicorn handler when running locally

### ISSUE THREAD

**Issue by asynchroza** [AUBGTheHUB/monolith#494]
## Brief description:
When using a logger with level INFO, logs won't get displayed by the uvicorn handler. 
When using a higher level, a log will get displayed but with no applied formatting at all. 
Additionally, I think it will be a good idea to have the handler show the name of the current logger.

E.g. `[INFO][auth]: Running authentication locally`

**Comment by IvanObreshkov** [comment]
> ## Brief description:
> When using a logger with level INFO, logs won't get displayed by the uvicorn handler. When using a higher level, a log will get displayed but with no applied formatting at all. Additionally, I think it will be a good idea to have the handler show the name of the current logger.
> 
> E.g. `[INFO][auth]: Running authentication locally`

Apperantly Uvicorn has their custom implementation of the use of colors. (INFO being green for example). If you would look like the format to be `[INFO][auth]: Running authentication locally` it will look like this -> 
![image](https://github.com/AUBGTheHUB/monolith/assets/38375079/97012379-1554-4463-b182-0dc423f8ac2d)

Tbh, I hate the whitespace. The other option is to leave it like that -> 
![image](https://github.com/AUBGTheHUB/monolith/assets/38375079/f23d5a71-a798-49bb-9c25-68bba0098c3a)

If you really want the format  `[INFO][auth]: Running authentication locally` Option 1 is this (look at the `health` logger )
![image](https://github.com/AUBGTheHUB/monolith/assets/38375079/ba858a56-d4b6-4759-99f7-2c985a7aba08) or Option 2 is to override uvicorn's [default implementation](https://github.com/encode/uvicorn/blob/master/uvicorn/logging.py#L64) of the colors.

**Comment by asynchroza** [comment]
> > ## Brief description:
> > When using a logger with level INFO, logs won't get displayed by the uvicorn handler. When using a higher level, a log will get displayed but with no applied formatting at all. Additionally, I think it will be a good idea to have the handler show the name of the current logger.
> > E.g. `[INFO][auth]: Running authentication locally`
> 
> @asynchroza Apperantly Uvicorn has their custom implementation of the use of colors. (INFO being green for example). If you would look like the format to be `[INFO][auth]: Running authentication locally` it will look like this -> ![image](https://user-images.githubusercontent.com/38375079/264081281-97012379-1554-4463-b182-0dc423f8ac2d.png)
> 
> Tbh, I hate the whitespace. The other option is to leave it like that -> ![image](https://user-images.githubusercontent.com/38375079/264083344-f23d5a71-a798-49bb-9c25-68bba0098c3a.png)
> 
> If you really want the format `[INFO][auth]: Running authentication locally` Option 1 is this (look at the `health` logger ) ![image](https://user-images.githubusercontent.com/38375079/264083790-ba858a56-d4b6-4759-99f7-2c985a7aba08.png) or Option 2 is to override uvicorn's [default implementation](https://github.com/encode/uvicorn/blob/master/uvicorn/logging.py#L64) of the colors.

@IvanObreshkov is it possible to import uvicorn's formatter and overwrite the `ColourizedFormatter`'s function `formatMessage`?

```python
from uvicorn.logging import ColourizedFormatter


def formatMessage(self, record: logging.LogRecord) -> str:
        recordcopy = copy(record)
        levelname = recordcopy.levelname
        seperator = " " * (8 - len(recordcopy.levelname))
        if self.use_colors:
            levelname = self.color_level_name(levelname, recordcopy.levelno)
            if "color_message" in recordcopy.__dict__:
                recordcopy.msg = recordcopy.__dict__["color_message"]
                recordcopy.__dict__["message"] = recordcopy.getMessage()
        recordcopy.__dict__["levelprefix"] = levelname + "::::" + seperator
        return super().formatMessage(recordcopy)

ColourizedFormatter.formatMessage = formatMessage
```

I've tried it but calling `super()` here fails but I'm sure we can figure it out. It's an interesting problem to explore. I'm willing to hop on a call with you to further investigate this if you wish.
