### ISSUE TITLE
[FEATURE] Exception handler is not logging any information for the request being made

### ISSUE THREAD

**Issue by asynchroza** [AUBGTheHUB/monolith#495]
## Brief description:
As of now, the exception handler will display full traceback but this is not enough when debugging failing requests. 

We need:
- [x] Full url -> this will tell us whether there are any query or path parameters present in the request
- [x] Method type

Additional:
Extract the logic from the health routes into controllers

**Comment by IvanObreshkov** [comment]
@Aleks1908 You said you wanted to try something from the backend. I believe you can tackle this issue easily. Please try without ChatGPT first. 😃

**Comment by asynchroza** [comment]
Pasting this here if it ever comes to us needing the exception handling decorator again - https://github.com/AUBGTheHUB/monolith/pull/502
