### ISSUE TITLE
[BUG] Logger doesn't work in dev

### ISSUE THREAD

**Issue by IvanObreshkov** [AUBGTheHUB/monolith#531]
## Brief description:
I believe the logger doesn't work properly, the last logged message is at 20:00. We could alao add dates to teh logger

**Comment by asynchroza** [comment]
No new logs are getting stored when you make failing requests?

**Comment by IvanObreshkov** [comment]
> No new logs are getting stored when you make failing requests?

Yes, I believe so. At least that is what the logfile in dev showed

**Comment by IvanObreshkov** [comment]
My bad
