### ISSUE TITLE
[BUG] Error with accessing protected routes still persists

### ISSUE THREAD

**Issue by IvanObreshkov** [AUBGTheHUB/monolith#539]
## Brief description:
Despite the changes in the nginx.conf the error is still  there: 
![image](https://github.com/AUBGTheHUB/monolith/assets/38375079/82c6b86f-dbec-4cdd-b293-07b58530ea67)

## How to achieve it:
Figure it out. Remove the hosts from the nginx.conf and change the logic in the auth.py file.

**Comment by asynchroza** [comment]
I believe the issue happens only locally since the logic is deployed on dev. 
The bug before was caused by using an incorrect url while this one uses the correct one but the api is not responding.
