### ISSUE TITLE
Add participant to team only after they have verified their email

### ISSUE THREAD

**Issue by IvanObreshkov** [AUBGTheHUB/monolith#591]
## Brief description:
* Create a team only after the person has verified their email.
* Add randoms to a random team only after they have verified their email

## How to achieve it:
* Use the functions located in `packages/py-api/py_api/functionality/hackathon/teams/
* Check the number of allowed users before creating a team and adding a participant
* As we don't have a verify endpoint yet create a mock route to test the functionality. Imagine that they have verified their email.

**Comment by asynchroza** [comment]
@IvanObreshkov you're giving people tickets which are too broad without providing any valuable information to what should actually be done. I will be closing this ticket out and break down this one is sub tickets.
