### ISSUE TITLE
Implement worflow for invite participant to a team

### ISSUE THREAD

**Issue by IvanObreshkov** [AUBGTheHUB/monolith#603]
## Brief description:
![image](https://github.com/AUBGTheHUB/monolith/assets/38375079/4d55bdad-045d-4adb-a1a1-076bbab3bd1b)
## How to achieve it:
:warning: Keep in mind that this is a sample function and you should come up with a better name
![image](https://github.com/AUBGTheHUB/monolith/assets/38375079/84d5f00c-8733-4b68-8f05-60e4e85e12b1)

**Comment by asynchroza** [comment]
This doesn't make sense. To be revisioned.
