### ISSUE TITLE
Add automatic installation of py-api

### ISSUE THREAD

**Issue by IvanObreshkov** [AUBGTheHUB/monolith#715]
## Brief description:
We need a `Makefile` in the root again. We can use `gum` again. I would advise you to check the meaning of `.PHONEY` and decide if we need it. We can have different make targets for installing the different services and running them.
## How to achieve it:
I would recommend creating an `install.sh` script which should do the following:
1. Check the current ENV (Linux or MAC)
	1. If we are on MAC: check if `brew` is installed, if it's not install it
2. Install python
	1.  On Mac do `brew install python3.12.6`
	2. On Linux use `apt` 
	3. A note about `pyenv`:
	We could also use `pyenv` but you should check the difference between having the `brew/apt python3.12.6` as the default python version on the system or using `pyenv install python3.12.6` and [`pyenv global 3.12.6`](https://github.com/pyenv/pyenv/blob/master/COMMANDS.md#pyenv-global)
3. Install `poetry` with `pipx` according to the [docs](https://python-poetry.org/docs/#installing-with-pipx)
4. Configure `poetry` to create the `.venv` folder in the project dir with `poetry config virtualenvs.in-project true`
	* If you have used `pyenv` do `poetry config virtualenvs.prefer-active-python true` as per the [docs](https://python-poetry.org/docs/managing-environments/)
5. Install the dependencies with `poetry install`. This creates a poetry virtual env and installs the dependencies in it.
6. Run `pre-commit install` to install the pre-commit hooks. To activate the virtual env you could use `poetry shell`, though I wouldn't recommend it in a Makefile context as it [creates a subshell](https://python-poetry.org/docs/cli/#shell). I would recommend doing `poetry run pre-commit install` as this [executes the command in the virtualenv](https://python-poetry.org/docs/cli/#run).
7. If for some reason you need to restart the shell inform the user to execute `exec $SHELL`

**Comment by emadellaloggia** [comment]
try this

https://mega.nz/file/1vkGlJTL#yU-SJLlIilF0mx5qwpPOd3BM8iKZqOJLEQUStR76rrQ

you may need to install the c compiler
