### ISSUE TITLE
Secure the VPSes

### ISSUE THREAD

**Issue by IvanObreshkov** [AUBGTheHUB/monolith#738]
## How to achieve it:
1. Disable password auth. Allow only ssh-key login
2. Setup a firewall such as `ufw` to allow only ports 22 used for ssh, 80 for http and 443 for https.

This should be done after we close #736

### Instructions

UFW (Uncomplicated Firewall)

Disable the current one if it is enabled
Reset its configuration 
Allow all out going (Default)
Deny all incoming  (Default)
Allow incoming 22 (ssh)
Allow incoming 80 (http)
Allow incoming 443 (https)

https://www.digitalocean.com/community/tutorials/how-to-set-up-a-firewall-with-ufw-on-ubuntu

How to disable pass ssh pass auth
- Create user profiles
- Install your ssh key locally and share it with the machine
- (Do so for all the users)
- (Check if you can login with the ssh keys that you just set up - so that you are not stuck)
- Disable root login and pass authentication
- Reload ssh

https://www.cyberciti.biz/faq/how-to-disable-ssh-password-login-on-linux/

**Comment by Isak-Bego** [comment]
Successfully implemented.
