### ISSUE TITLE
Add Unique Transaction ID to the logs

### ISSUE THREAD

**Issue by IvanObreshkov** [AUBGTheHUB/monolith#757]
## Brief description:
As of now the logs look like this locally (in the terminal):
<img width="1379" alt="image" src="https://github.com/user-attachments/assets/c44c31a5-d270-4769-8acf-1262bddf019b">
And this is how they are written to a file (on the VMs):
<img width="1320" alt="image" src="https://github.com/user-attachments/assets/a6035145-240b-499b-b8ea-b5940ed00e9b">

Now imagine if we have multiple instances of the API writing to that log file or if some of the logs get delayed and are written later (not in sequential order as above), and you have hundreds of these transactions. It becomes quite difficult to trace which particular transaction has started, been committed, or aborted, that's why we have to append a transaction ID to every transaction when it starts and so on.
## How to achieve it:
For the unique ID, you could use [uuid module](https://docs.python.org/3/library/uuid.html) in Python.

You could also be more verbose in the logs, for example, `LOG.debug("Inserting team {team_entity} via transaction", transaction_id = "12345678-1234-5678-1234-567812345678")`

**Comment by Isak-Bego** [comment]
After consultation with @asynchroza we will abandon this approach
