### ISSUE TITLE
Implement signing of requests

### ISSUE THREAD

**Issue by IvanObreshkov** [AUBGTheHUB/monolith#761]
## Brief description:
We need something similar to https://docs.aws.amazon.com/AmazonS3/latest/API/sig-v4-authenticating-requests.html

Why: 
As @Isak-Bego mentioned, it's a good idea to restrict our API only to requests coming from the React front-end. This could be done by signing requests, a common technique used in service-to-service communication in a distributed env. 

## How to achieve it
1. The front-end should have logic for signing the requests using a secret and different parts of the request. 
2. Store the hash in the Authorization header or a custom one starting with `X-` as per https://www.keycdn.com/support/custom-http-headers when sending the request towards the API
3. The backend should have a similar logic for computing the digest of the requests and a way to compare the two generated hashes. 
4. If the hashes don't match return a 401 or 403 status code
5. The backend should have a logic to bypass this when in testing env or when testing locally

**Comment by Isak-Bego** [comment]
@IvanObreshkov I suggest we close this. We don't really need to sign the requests that are coming to our public endpoints, as it was just a misconception on our side.

**Comment by asynchroza** [comment]
> The front-end should have logic for signing the requests using a secret and different parts of the request.


What are you guys going on about? How would a client side request have a secret?

**Comment by asynchroza** [comment]
This server to server authentication. Not client to server.

**Comment by Isak-Bego** [comment]
@asynchroza @IvanObreshkov @Pastedko @cl3vy we are closing this as it is not applicable to our usecase.
