### ISSUE TITLE
Install React-Hook-Form and Zod libraries

### ISSUE THREAD

**Issue by Aleks1908** [AUBGTheHUB/monolith#775]
## Brief description:
React-hook-form is a library we are going to be using to make our lives easier for verifying and sending information from form inputs. Zod is a schema validating library which works with React-hook-form to validate the inputs
## How to achieve it:
- Read the documentations of both libraries. Go to the front-end part of the project and install the libraries.
- [React-hook-form](https://react-hook-form.com/)
- [Zod](https://zod.dev/)

**Comment by asiahaslam** [comment]
I installed the libraries.
