### ISSUE TITLE
[Internal lib] Research and implement a reusable input component

### ISSUE THREAD

**Issue by Aleks1908** [AUBGTheHUB/monolith#776]
## Brief description:
We are going to be making an internal library for form elements. Research how you can do that based on the documentation of [shadcn](https://ui.shadcn.com/docs/components/input) and [React-hook-form](https://react-hook-form.com/). The general idea is for these components to be fully reusable and to accept props for everything. So that we can not only use them in the HackAUBG page but in the admin panel in the future. You would also have to write tests with all the edge cases to verify that the inputs are working correctly. If you have any questions don't hesitate to ask @Aleks1908

## What needs to be done
The input component should be able to be used as a input for:
- Text
- Numbers 
- Emails
- Passwords

**Comment by iobreshkov-qb** [comment]
I suggest creating a separate repo for internal libraries and pushing them to an artifactory, just to make our lives easier and not introduce complexity.

**Comment by Aleks1908** [comment]
I think for such library it wont be needed to separate it. This library is going to tied to the project, its not going to be reused in other projects. And if we separate it in a different repo it will introduce additional overhead. Keeping the internal lib inside the repo will make it much easier for us to develop it and test it. If the library expands to something bigger in the future we can still separate it but for the moment I don't think it will be needed.

**Comment by IvanObreshkov** [comment]
> I think for such library it wont be needed to separate it. This library is going to tied to the project, its not going to be reused in other projects. And if we separate it in a different repo it will introduce additional overhead. Keeping the internal lib inside the repo will make it much easier for us to develop it and test it. If the library expands to something bigger in the future we can still separate it but for the moment I don't think it will be needed.

More overhead and more complexity = better Developer Experience and Staff engineering

**Comment by Aleks1908** [comment]
Thank you for your opinion but we are going to stick with having them inside the repo for now.
