### ISSUE TITLE
[CRITICAL] Remove fontend tests running on commit

### ISSUE THREAD

**Issue by Isak-Bego** [AUBGTheHUB/monolith#796]
## Brief description:
Reasons: 
1. They will run no matter if we have changed any of the front end files or not, thus slowing the whole team when committing, especially when considering the increasing number of tests
2. They can be easily skipped by the person who is committing, making us unsure if all the tests have really passed or not. We would have to manually go to their branch and run the tests to be sure. 
## How to achieve it:
Follow a similar methodology as we have followed with the github workflow for the back end tests. It is faster since the committing process is not being delayed and you cannot skip them. 

This stack exchange from 10 years ago discusses on this topic and arrives in the same conclusion: https://softwareengineering.stackexchange.com/questions/260778/is-it-a-good-practice-to-run-unit-tests-in-version-control-hooks

**Comment by asynchroza** [comment]
You can update them to run only if the tests are relevant to the affected code.

**Comment by asynchroza** [comment]
> They can be easily skipped by the person who is committing, making us unsure if all the tests have really passed or not. We would have to manually go to their branch and run the tests to be sure.

If you want to ensure that, add a CI action.

**Comment by asynchroza** [comment]
> Follow a similar methodology as we have followed with the github workflow for the back end tests. It is faster since the committing process is not being delayed and you cannot skip them.

Be mindful that you only have 1000 minutes a month to use in github actions.

**Comment by Isak-Bego** [comment]
Issue moved to #820
