### ISSUE TITLE
Cannot access action endpoint when url is pasted in new tab

### ISSUE THREAD

**Issue by asynchroza** [AUBGTheHUB/monolith#98]
## Brief description:
When directly accessing `/admin/dashboard/<section>/actions` endpoint (copy pasting the url to another browser/tab), page doesn't get rendered because location [state](https://github.com/AUBGTheHUB/spa-website-2022/blob/3a0e12132f8238d7b4463edc2bcb173842d130f1/packages/web/src/components/admin_page/articles_page/actions_articles.jsx#L11) is null (page is trying to access them). 

<img width="552" alt="image" src="https://user-images.githubusercontent.com/104720011/204797466-0738bba8-0d4c-4b67-bce1-22cd3e972a89.png">

## How to achieve it:
Check whether location [state](https://github.com/AUBGTheHUB/spa-website-2022/blob/3a0e12132f8238d7b4463edc2bcb173842d130f1/packages/web/src/components/admin_page/articles_page/actions_articles.jsx#L11) is null, if so redirect to current url without the last chained endpoint.  

e.g. `/admin/dashboard/members/actions` -> location.state is null -> `/admin/dashboard/members`

Define this as a utility function which could be passed an argument (location.state). It should be saved in a file in the root of `admin_page`. 

[Check this file for an example on how to export variables/functions](https://github.com/AUBGTheHUB/spa-website-2022/blob/master/packages/web/src/Global.js)

**Comment by mbozhilov-qb** [comment]
admin/dashboard/sponsors without a token seems to get stuck at a white screen as well instead of showing client is not validated

**Comment by asynchroza** [comment]
Bringing this as medium priority. This is an easy ticket to tackle but it's probably going to take a lot of time for @IvanObreshkov to get familiar with the frontend codebase. @Aleks1908 would want to tackle this after the hackathon? @IvanObreshkov if you want new challenges this is a great ticket for the time span before we start exploring cloud functions and other development stories we need to get on.

**Comment by IvanObreshkov** [comment]
> Bringing this as medium priority. This is an easy ticket to tackle but it's probably going to take a lot of time for @IvanObreshkov to get familiar with the frontend codebase. @Aleks1908 would want to tackle this after the hackathon? @IvanObreshkov if you want new challenges this is a great ticket for the time span before we start exploring cloud functions and other development stories we need to get on. 

Sure thing
